"""
CodeLens — Markdown & HTML Exporters
One-click export of generated documentation to Markdown and HTML.
"""
import logging
from pathlib import Path

logger = logging.getLogger(__name__)


class MarkdownExporter:
    """Exports generated documentation to clean Markdown files."""

    def export(self, docs: dict[str, dict], output_dir: str) -> list[str]:
        """
        Export documentation to Markdown files.

        Args:
            docs: Dict mapping file paths to their generated docs
            output_dir: Directory to write Markdown files

        Returns:
            List of generated file paths
        """
        out = Path(output_dir)
        out.mkdir(parents=True, exist_ok=True)
        generated_files = []

        for file_path, module_docs in docs.items():
            module_name = Path(file_path).stem
            md_path = out / f"{module_name}.md"

            lines = [
                f"# {module_name}\n",
                f"{module_docs.get('module_doc', '_No module documentation._')}\n\n",
            ]

            # Functions
            if module_docs.get("functions"):
                lines.append("## Functions\n")
                for func_name, doc in module_docs["functions"].items():
                    lines.append(f"### `{func_name}`\n")
                    lines.append(f"{doc}\n\n")

            # Classes
            if module_docs.get("classes"):
                lines.append("## Classes\n")
                for class_name, class_docs in module_docs["classes"].items():
                    lines.append(f"### `{class_name}`\n")
                    lines.append(f"{class_docs.get('class_doc', '')}\n\n")

                    if class_docs.get("methods"):
                        lines.append("#### Methods\n")
                        for method_name, method_doc in class_docs["methods"].items():
                            lines.append(f"##### `{method_name}`\n")
                            lines.append(f"{method_doc}\n\n")

            md_path.write_text("".join(lines), encoding="utf-8")
            generated_files.append(str(md_path))
            logger.info(f"Markdown exported: {md_path}")

        return generated_files


class HTMLExporter:
    """Exports generated documentation to self-contained HTML pages."""

    HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>CodeLens — {module_name}</title>
<style>
  * {{ box-sizing: border-box; margin: 0; padding: 0; }}
  body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
          background: #0f172a; color: #e2e8f0; line-height: 1.6; }}
  .container {{ max-width: 900px; margin: 0 auto; padding: 2rem; }}
  h1 {{ color: #38bdf8; font-size: 2rem; margin-bottom: 0.5rem; }}
  h2 {{ color: #94a3b8; font-size: 1.3rem; margin: 2rem 0 1rem;
        border-bottom: 1px solid #1e293b; padding-bottom: 0.5rem; }}
  h3 {{ color: #7dd3fc; font-size: 1.1rem; margin: 1.5rem 0 0.5rem; }}
  h4 {{ color: #64748b; margin: 1rem 0 0.3rem; }}
  .doc {{ background: #1e293b; border-radius: 8px; padding: 1rem 1.5rem;
          margin: 0.5rem 0; border-left: 3px solid #38bdf8; font-size: 0.95rem; }}
  code {{ background: #0f172a; padding: 0.1rem 0.4rem; border-radius: 4px;
          font-family: 'Fira Code', monospace; color: #a5f3fc; }}
  .badge {{ background: #1e40af; color: #bfdbfe; padding: 0.2rem 0.6rem;
             border-radius: 999px; font-size: 0.75rem; margin-left: 0.5rem; }}
  footer {{ margin-top: 4rem; color: #475569; font-size: 0.85rem; text-align: center; }}
</style>
</head>
<body>
<div class="container">
<h1>🔍 {module_name}</h1>
<div class="doc">{module_doc}</div>
{content}
<footer>Generated by <strong>CodeLens</strong> — AI-Powered Documentation Engine</footer>
</div>
</body>
</html>"""

    def export(self, docs: dict[str, dict], output_dir: str) -> list[str]:
        out = Path(output_dir)
        out.mkdir(parents=True, exist_ok=True)
        generated_files = []

        for file_path, module_docs in docs.items():
            module_name = Path(file_path).stem
            html_path = out / f"{module_name}.html"

            sections = []

            if module_docs.get("functions"):
                sections.append("<h2>Functions</h2>")
                for func_name, doc in module_docs["functions"].items():
                    sections.append(f"<h3><code>{func_name}</code></h3>")
                    sections.append(f'<div class="doc">{doc}</div>')

            if module_docs.get("classes"):
                sections.append("<h2>Classes</h2>")
                for class_name, class_docs in module_docs["classes"].items():
                    sections.append(
                        f'<h3><code>{class_name}</code>'
                        f'<span class="badge">class</span></h3>'
                    )
                    sections.append(f'<div class="doc">{class_docs.get("class_doc", "")}</div>')

                    if class_docs.get("methods"):
                        sections.append("<h4>Methods</h4>")
                        for method_name, method_doc in class_docs["methods"].items():
                            sections.append(f"<h4><code>{method_name}</code></h4>")
                            sections.append(f'<div class="doc">{method_doc}</div>')

            html = self.HTML_TEMPLATE.format(
                module_name=module_name,
                module_doc=module_docs.get("module_doc", ""),
                content="\n".join(sections),
            )
            html_path.write_text(html, encoding="utf-8")
            generated_files.append(str(html_path))
            logger.info(f"HTML exported: {html_path}")

        return generated_files
